// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbums(arg1:string):Promise<Array<string>>;

export function GetDirPath():Promise<string>;
