// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {player} from '../models';

export function GetAlbum(arg1:string):Promise<catalog.Album>;

export function GetAlbums(arg1:string):Promise<Array<string>>;

export function GetCatalog(arg1:string):Promise<catalog.Catalog>;

export function GetCurrentTrack(arg1:string):Promise<catalog.Track>;

export function GetDirPath():Promise<string>;

export function GetMusicDirPath():Promise<string>;

export function GetPlaylist(arg1:string):Promise<player.Playlist>;

export function IsDBAvailable():Promise<boolean>;

export function LoadCatalogFromDB():Promise<catalog.Catalog>;

export function NewDB():Promise<void>;

export function NewPlaylist(arg1:Array<catalog.Track>):Promise<player.Playlist>;

export function NextTrack(arg1:string):Promise<void>;

export function PauseSong(arg1:string):Promise<void>;

export function Play(arg1:string):Promise<void>;

export function PreviousTrack(arg1:string):Promise<void>;

export function ResumeSong(arg1:string):Promise<void>;

export function SaveCatalog(arg1:catalog.Catalog):Promise<void>;

export function SyncDB():Promise<void>;
