// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbums(arg1) {
  return window['go']['main']['App']['GetAlbums'](arg1);
}

export function GetDirPath() {
  return window['go']['main']['App']['GetDirPath']();
}

export function GetTrackInfo(arg1) {
  return window['go']['main']['App']['GetTrackInfo'](arg1);
}
