// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbum(arg1) {
  return window['go']['main']['App']['GetAlbum'](arg1);
}

export function GetAlbums(arg1) {
  return window['go']['main']['App']['GetAlbums'](arg1);
}

export function GetCatalog(arg1) {
  return window['go']['main']['App']['GetCatalog'](arg1);
}

export function GetDirPath() {
  return window['go']['main']['App']['GetDirPath']();
}

export function GetTrack(arg1) {
  return window['go']['main']['App']['GetTrack'](arg1);
}

export function PauseSong(arg1) {
  return window['go']['main']['App']['PauseSong'](arg1);
}

export function PlaySong(arg1) {
  return window['go']['main']['App']['PlaySong'](arg1);
}
